### ISSUE TITLE
Interface support 

### ISSUE THREAD

**Issue by mandado** [freshgum-bubbles/typedi#143]
**Is your question related to a contrib/ feature?**

No

**Question**

it's will be injection supported using the interface instead of classes in some version, or is it already possible?

**Comment by freshgum-bubbles** [comment]
Hmm, I'm not sure what you mean.  Do you have a specific example in mind?

freshgum

**Comment by freshgum-bubbles** [comment]
Just checking in: did you fix your issue?

freshgum

**Comment by mandado** [comment]
Sorry for late response,

I'll send an example later! :)

**Comment by JonathanIlk** [comment]
Not the OP, but I assume what he is requiring is something like the Spring Boot Injection mechanism for Interfaces.

Step 1: Define Interface `IServiceA`
Step 2: Define class implementing said interface `class ServiceA_Impl1 implements IServiceA`
Step 3: Define another class implementing said interface `class ServiceA_Impl2 implements IServiceA`
Step 4: Create `ServiceB` that depends on `IServiceA`
Step 5: Define which Implementation should be injected in a `@Bean`

The advantages of this, would be that Services can be easily mocked by creating a second implementation of IServiceA.
E.g. `Impl1` could access data from a database used in Production and `Impl2` could simply mock a database connection and be used for tests.

For Reference how it works in Spring Boot: https://www.javaguides.net/2023/06/using-interface-as-dependency-in-spring.html

**Comment by mandado** [comment]
@freshgum-bubbles  the idea it's todo something like that:

```
import { Service } from "freshgum/typedi";

export interface ILogService {
	log(message: string): string;
}

@Service([])
export class DeepLogService {
	public log(message: string) {
		return message;
	}
}

@Service([DeepLogService])
export class LogService {
	constructor(private deepLogService: ILogService) {}

	public log(message: string) {
		return this.deepLogService.log(message);
	}
}
```

**Comment by freshgum-bubbles** [comment]
> Not the OP, but I assume what he is requiring is something like the Spring Boot Injection mechanism for Interfaces.
> 
> Step 1: Define Interface `IServiceA`
> Step 2: Define class implementing said interface `class ServiceA_Impl1 implements IServiceA` 
> Step 3: Define another class implementing said interface `class ServiceA_Impl2 implements IServiceA` 
> Step 4: Create `ServiceB` that depends on `IServiceA` 
> Step 5: Define which Implementation should be injected in a `@Bean`

That makes sense, and it's definitely a use-case which could be better catered-to.
The best solution I can think of would be a `Token`, which you then set to point at
the implementation you want to use.

What about something like this:

```ts
/* eslint-disable no-console */
import { Container, Service, Token } from "@freshgum/typedi";

// Interface for our implementations:
export interface ILogService {
	log(message: string): string;
}

// Implementation 1:
@Service([ ])
export class FakeLogService implements ILogService {
	public log(message: string) {
		return message;
	}
}

// Implementation 2:
@Service([ ])
export class ConsoleLogService implements ILogService {
    public log (message: string) {
        console.log(message);
        return message;
    }
}

// Create a token for the log service used in the implementation:
const LOGGER = new Token<ILogService>('The logger for the application.');

// Use the token as a dependency instead of using the concrete
// implementations (e.g. ConsoleLogService):
@Service([LOGGER])
export class LogService {
	constructor(private deepLogService: ILogService) {}

	public log(message: string) {
		return this.deepLogService.log(message);
	}
}

// In your composition root...
Container.set({
    id: LOGGER,
    factory: () => Container.get(process.env.NODE_ENV === 'development' ? ConsoleLogService : FakeLogService)
});
```

This isn't perfect, though: I can definitely see the `.set` calls making a big mess
of your composition root as the size of your code-base increases.
If the above fits your requirements, I could probably be swayed into adding a
helper (`.alias`?) to make it easier and more obvious that this is possible.

**Comment by mandado** [comment]
What dou you think in api surface for this example ?

**Comment by freshgum-bubbles** [comment]
> What dou you think in api surface for this example ?

If you mean what I could add to make the above easier, I was thinking of creating an `alias` function / method, which would add a service to the container that points at another service.

Something like this:

```ts
function alias (container: ContainerInstance, alias: ServiceIdentifier, target: ServiceIdentifier) {
  container.set({ id: alias, factory: () => container.get(target) });
}
```

<sup>(of course, the typing would need to be a lot stricter, but that's the gist.)</sup>

Then, you'd run it on your alias above like so:

```ts
alias(Container, LOGGER, process.env.NODE_ENV === 'development' ? ConsoleLogService : FakeLogService);
```

What do you think?

**Comment by mandado** [comment]
> > What dou you think in api surface for this example ?
> 
> If you mean what I could add to make the above easier, I was thinking of creating an `alias` function / method, which would add a service to the container that points at another service.
> 
> Something like this:
> 
> ```ts
> function alias (container: ContainerInstance, alias: ServiceIdentifier, target: ServiceIdentifier) {
>   container.set({ id: alias, factory: () => container.get(target) });
> }
> ```
> 
> (of course, the typing would need to be a lot stricter, but that's the gist.)
> 
> Then, you'd run it on your alias above like so:
> 
> ```ts
> alias(Container, LOGGER, process.env.NODE_ENV === 'development' ? ConsoleLogService : FakeLogService);
> ```
> 
> What do you think?

LGTM, but the container will be necessary ?

**Comment by freshgum-bubbles** [comment]
> LGTM, but the container will be necessary ?

Yes, containers are a fundamental concept of DI :-)

**Comment by mandado** [comment]
I mean, will needed to pass as parameter the container ?

**Comment by freshgum-bubbles** [comment]
With the above function, yes: you would need to pass it as a parameter :-)
If your app container is just the default one, then you can always use `Container`.

P.S. You could always move around the arguments to `alias` to put the
container last, and then add `= Container` to that parameter, which would
make it default to the... *default* container when a container isn't passed.

**Comment by freshgum-bubbles** [comment]
Hi, marking this as solved if that's all :)
