### ISSUE TITLE
Support typescript stage 3 decorator ？

### ISSUE THREAD

**Issue by ikilobyte** [freshgum-bubbles/typedi#162]
I'm going to use stage 3 decorator in my typescript project with inversify, but can't not use stage 2 and stage 3 decorator at the same time.Any plan to support stage 3 decorator?

**Comment by ikilobyte** [comment]
TypeScript 5.2 support decorator metadata

**Comment by freshgum-bubbles** [comment]
Hello, this was already answered in https://github.com/freshgum-bubbles/typedi/issues/153.
